### ISSUE TITLE
Best practices for naming workers, subjects

### ISSUE THREAD

**Issue by shilov** [nats-io/nats-site#116]
Suggestion: expand documentation to add examples or best practices for naming workers, subjects.

**Comment by andyfleming** [comment]
Along the same lines, it says `no embedded whitespace` on the [NATS Client Protocol](https://nats.io/documentation/internals/nats-protocol/) page when talking about subject names, but it would be nice to explicitly call out whether underscores and hyphens are allowed.

**Comment by gcolliso** [comment]
updating new docs - nats-io/docs/nats_protocol/nats-protocol.md

**Comment by 300LiterPropofol** [comment]
Hi!
The link above is broken. I can not find anything about whether underscores & hyphens are allowed or not in the doc.
Please help.

Is there an answer to the above question?

**Comment by gcolliso** [comment]
@300LiterPropofol the new docs are located at https://docs.nats.io, specifically the protocol page above is at https://docs.nats.io/reference/reference-protocols/nats-protocol
