### ISSUE TITLE
Go client does not work with queueing examples

### ISSUE THREAD

**Issue by invisibleroads** [nats-io/nats-site#121]
The [documentation listed here](http://nats.io/documentation/tutorials/nats-queueing/) says that the following commands should subscribe to the "foo" subject on the "my-queue" queue.

    cd $GOPATH/src/github.com/nats-io/nats/examples
    go run nats-sub.go foo my-queue

However, looking at the code for [nats-sub.go](https://github.com/nats-io/nats/blob/master/examples/nats-sub.go), it looks like the second argument is ignored, resulting in all the clients receiving the published message, when what was expected was that only one client would receive the message.

However, the Python client works as expected.

    python examples/nats-sub foo -q my-queue

**Comment by mcqueary** [comment]
Good catch. The issue is that the queue subscriber was moved into a separate example. It should be `go run nats-qsub.go foo my-queue`. We'll fix. Thanks!
