### ISSUE TITLE
Move Clients into Download

### ISSUE THREAD

**Issue by mcqueary** [nats-io/nats-site#15]
We should add all the information that is in the [Clients](http://nats.io/clients/) page to the [Download](http://nats.io/download/) page, and do away with the separate Clients page and menu item.

The Downloads page should simply have a Server section (with the gnatsd links) and Clients section (with all the client info/links).

/cc @derekcollison @chriscasper

**Comment by chriscasper** [comment]
Will take a look at this. Will be a simple change.

**Comment by chriscasper** [comment]
This is ready for review: https://github.com/nats-io/nats-site/pull/19

**Comment by chriscasper** [comment]
Here is a screenshot of it: 

![image](https://cloud.githubusercontent.com/assets/91715/11226924/e5b10440-8d37-11e5-98c5-fec17e3e13ee.png)

**Comment by kozlovic** [comment]
LGTM

**Comment by chriscasper** [comment]
This is now completed and live. http://nats.io/

**Comment by derekcollison** [comment]
Nice!
