### ISSUE TITLE
Minor notes on `content/documentation/index.md`

### ISSUE THREAD

**Issue by ShawnMilo** [nats-io/nats-site#182]
"NATS Clients" section: It would be nice if there were recommended community clients for languages not directly supported by Apcera. Similar to how [Redis](http://redis.io/clients) does it. This wouldn't imply that Apcera supports these, but would make a developer feel much more comfortable downloading a third-party client.

"NATS use cases" section: Where possible, brief, plain-English examples of the bullet points would help people understand the capabilities, and would be more likely to cause them to continue reading and download NATS. Also, typo: "High througput message fanout" (missing "h" in throughput).

**Comment by mcqueary** [comment]
@ShawnMilo that's an excellent point. We actually link to those on the [Download](http://nats.io/download/) page, which would be your most complete and up-to-date source, generally. Perhaps we should eliminate the page you're referring to in favor of a link to the download page. This has come up before. 

Thanks for the other suggestions; we'll definitely look at those.

**Comment by mcqueary** [comment]
See #184
