### ISSUE TITLE
Single page for NATS clients

### ISSUE THREAD

**Issue by mcqueary** [nats-io/nats-site#186]
As pointed out in #182, the [NATS Clients](https://nats.io/documentation/clients/nats-clients/) page duplicates a subset of the information contained on the [Download](https://nats.io/download) page, which is usually guaranteed to be up-to-date. 

We should  keep the Download page as the authoritative, up-to-date resource for information on the server and clients, and retire the separate NATS Clients page.

@ColinSullivan1 @kozlovic @aricart @bjflanne @wallyqs @derekcollison please weigh in

**Comment by kozlovic** [comment]
@mcqueary No objection.
