### ISSUE TITLE
Missing reference to Python in clients list

### ISSUE THREAD

**Issue by chmike** [nats-io/nats-site#190]
Hello, 
in [this page](http://nats.io/documentation/clients/nats-clients/) a link to the Python client is missing. 
Only the link to a third party lib is provided and travis reports that it doesn't compile. 

But on the [Download page](http://nats.io/download/) the Python clients are listed. 

The absence of a python client would have been a show stopper for us. I was lucky I didn't stop my investigation at the first page. Could you please fix this *nats-client* page ?

**Comment by wallyqs** [comment]
Thanks, there are also plans on consolidating on a single download page which would prevent these being out of sync https://github.com/nats-io/nats-site/issues/186

**Comment by mcqueary** [comment]
Closed in favor of #186 solution. (Thanks Christophe!)
