### ISSUE TITLE
Documentation for older versions

### ISSUE THREAD

**Issue by Rickkwa** [nats-io/nats-site#224]
Have a dropdown or link for the user to choose what version of the software to view documentation for.

**Comment by mcqueary** [comment]
Hi Rick (@rickkwa) -- we strive to keep what's on the site up-to-date with with the latest versions of `gnatsd` and `nats-streaming-server`, and to do what you're asking would be a big change from how we're doing things today, so we'll need to think through that.  As a side note, some of the clients (like java and go) have their documentation hosted on sites that will allow you to do that. Which client are you using?

**Comment by ColinSullivan1** [comment]
We encourage users to keep up to date with the latest releases, and the documentation will follow the latest release.  That being said, this may be something we'll strive for after we hit major version bumps of our software (v 2.0.0).  Thank you for the suggestion.
