### ISSUE TITLE
Eliminate duplicate protocol info

### ISSUE THREAD

**Issue by mcqueary** [nats-io/nats-site#228]
The [NATS Server clustering protocol](https://github.com/nats-io/nats-site/blob/master/content/documentation/internals/nats-server-protocol.md) duplicates most of the [NATS protocol page](https://github.com/nats-io/nats-site/blob/master/content/documentation/internals/nats-server-protocol.md). These can be consolidated to avoid duplication. If any protocol message has a special meaning when exchanged between servers (vs. between client and server), it should be noted in the main document.

**Comment by ColinSullivan1** [comment]
@mcqueary I did this with some intent.  The protocol won't change much, so this doesn't pose any real maintenance issue, and if it does, there may be subtleties between the client and server that differ.  While they happen to be similar, in fact identical in cases, IMO, combining the client and server protocol pages may be confusing.  That being said, if you do find a way to make it clearer, absolutely feel free to reorganize.
