### ISSUE TITLE
what does NATS stand for?

### ISSUE THREAD

**Issue by dieseltravis** [nats-io/nats-site#237]
I'm assuming it's an acronym since it's in all-caps, but I can't find anywhere on the site where it defines the acronym. Maybe an FAQ can be added?

**Comment by ColinSullivan1** [comment]
Thanks for raising this issue; we'll update the FAQ.  NATS stands for Neural Autonomic Transport System. Derek Collison conceived NATS as a messaging platform that functions like a central nervous system.

**Comment by marcelluseasley** [comment]
The FAQ on the website states:
```
What does the NATS acronym stand for?

Ask a NATS maintainer at one of the many meetups and conferences we attend to discover the mystery and lore behind the NATS acronym.
```
which is crappy.

**Comment by alextes** [comment]
And what about STAN? What's up with that one?

**Comment by ripienaar** [comment]
Opposite of NATS - since nats is at most once and STAN is at least once.

**Comment by alextes** [comment]
Hah, I mean suggesting "at least once" is the equivalent of (not "at most once") is stretching it haha, but I can follow the idea. Thanks @ripienaar !
