### ISSUE TITLE
Instructions at "Build NATS Server from Source" are incorrect

### ISSUE THREAD

**Issue by VictorBarrantes** [nats-io/nats-site#251]
Step 3: "CD to the gnatsd directory you cloned." cd $GOPATH/src/github.com/nats-io/gnatsd
Wrong. . .  This directory does not exists in the source tree.

Step 4: "View the NATS server source code." Use command ls to list the gnatsd.go file.
Use command cat gnatsd.go to view the code.
Wrong. . .  The file gnatsd.go does not exists in the cloned source repo.

See: 
```
C:\Programs\Go\src\github.com\nats-io>dir gnatsd.go /s
 Volume in drive C is Windows
 Volume Serial Number is ACA3-EE57
File Not Found
```

That makes the rest of instructions at "http://nats.io/documentation/tutorials/nats-source/" useless.

**Comment by ColinSullivan1** [comment]
@VictorBarrantes , thank you, we'll look into this.

**Comment by gcolliso** [comment]
nats-server installation instructions have been updated here https://nats-io.github.io/docs/nats_server/installation.html#installing-from-the-source

Windows service here https://nats-io.github.io/docs/nats_server/windows_srv.html
