### ISSUE TITLE
how the get the ping example?

### ISSUE THREAD

**Issue by erikbgithub** [nats-io/nats-site#254]
On [the docker docs site](https://nats.io/documentation/tutorials/gnatsd-docker/) It says there is an example client that can be used to test the docker gnats container. However it only shows a path but not where the path comes from.

It says the executable would be in: `cd /nats-docs/tutorials/examples/`

I assume without testing that a vanilla Ubuntu 16.04 computer won't have a root directory called `/nats-docs/` (bold assumption, I know ;) ).

Also one might wonder why it's not just possible to "docker run nats-ping-example" or similar.

**Comment by erikbgithub** [comment]
Also the `docker run` would be reasonable in the background and with port forwarding,, wouldn't it? Otherwise one can't connect to the nats server.

**Comment by erikbgithub** [comment]
I'm also finished with the protocol now. Super easy to understand (awesome!), but that also means the docker doc could just end with a simple telnet example.

**Comment by ColinSullivan1** [comment]
@erikbgithub , Thank you for your interest in NATS!  We appreciate you creating this issue.  The `nats-ping.go` example is out is of date; we'll resolve this and double-check the docker configuration.  I appreciate your telnet suggestion in testing; that may be the way to go - Thanks!
