### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by lovew** [nats-io/nats-site#268]
![2017-08-08-102301_712x368_scrot](https://user-images.githubusercontent.com/7919712/29053620-aa34ff34-7c23-11e7-81a9-987b80a42198.png)

**Comment by ColinSullivan1** [comment]
I'm not seeing it; where is the typo?

**Comment by lovew** [comment]
@ColinSullivan1  well, watch, start, fork are the same number, maybe it is not typo in english ...

**Comment by ColinSullivan1** [comment]
@lovew , Ahh - I see now.  Typo in the english language usually refers to a misspelled word.  This is an issue nonetheless - thanks for pointing this out!

**Comment by ColinSullivan1** [comment]
@lovew , just getting back to this; I've checked and it looks OK to me....
![natsserverusage](https://user-images.githubusercontent.com/11180189/29946079-26aff97a-8e61-11e7-9614-903af1f0d0d2.jpg)

**Comment by lovew** [comment]
nice
