### ISSUE TITLE
Metrics from Github not displaying quite right on /download page

### ISSUE THREAD

**Issue by bjflanne** [nats-io/nats-site#271]
The #of stars is also being populated for the #of watchers and forks for NATS Server and NATS Streaming, instead of showing the accurate numbers.

**Comment by ColinSullivan1** [comment]
@bjflanne , could you verify it is still an issue for you...  I didn't see a commit fixing this; perhaps it was a GH issue?

I just checked:

![natsserverusage](https://user-images.githubusercontent.com/11180189/29946166-746069c0-8e61-11e7-84e5-bf84a173b1b2.jpg)
