### ISSUE TITLE
More use-case examples with sample scenarios

### ISSUE THREAD

**Issue by bjflanne** [nats-io/nats-site#283]
- Include some of the great examples @bruth had in his blog post (https://dev.to/byronruth/use-cases-for-persistent-logs-with-nats-streaming)

- We say in the docs 'Support for various messaging models and use cases (flexible)' - many would find a few examples useful there.. likewise, in the NATS Use Cases section on /doc page having an actual example to build on each scenario listed would really help. << via @ipedrazas

**Comment by bruth** [comment]
Closing as natsbyexample.com is the seed for this and will be expanding further in 2023.
