### ISSUE TITLE
Getting "Connection Is Not Private" on nats.io site

### ISSUE THREAD

**Issue by jscottsf** [nats-io/nats-site#355]
Getting `"*.nats.io" certificate name does not match input` when visiting the site on all browsers and also on mobile.

**Comment by aricart** [comment]
go ahead and force a reload. The certificate was updated and works fine for me on chrome, safari, opera, firefox and chrome mobile.

**Comment by aricart** [comment]
![image](https://user-images.githubusercontent.com/1032976/43428841-fd9d54ee-9425-11e8-9510-8f933e26bdda.png)

**Comment by jscottsf** [comment]
Yeah, works now in Chrome. Still having issues in Safari and Firefox even after deleting the cert from my keychain.

**Comment by gcolliso** [comment]
New certificate in place. Issue resolved
