### ISSUE TITLE
Question regarding NATS message formats

### ISSUE THREAD

**Issue by Ann-Geo** [nats-io/nats-site#397]
Hi,
I have a few questions regarding the functionality of NATS. Is it possible to send and receive .txt, .doc, or any other files directly using NATS? I saw in the documentation page that NATS server treats all messages as byte arrays (https://nats.io/documentation/writing_applications/publishing/). And some libraries may provide helpers to convert other data formats to and from bytes. If its possible to send and receive other formats of messages or files as such, then how can I do that? Please provide any documentation. Also is there any detailed design manual of NATS publicly available for beginners to understand the design concepts underlying the messaging system?

**Comment by gcolliso** [comment]
New documentation on Concepts can be found here [https://nats-io.github.io/docs/](https://nats-io.github.io/docs/.) Should you have specific questions, I would suggest joining our [Slack channel.](https://join.slack.com/t/natsio/shared_invite/enQtMzE2NDkxNDI2NTE1LTc5ZDEzYTkwYWZkYWQ5YjY1MzBjMWZmYzA5OGQxMzlkMGQzMjYxNGM3MWYxMjNiYmNjNzIwMTVjMWE2ZDgxZGM)
