### ISSUE TITLE
Request Reply one-to-many.

### ISSUE THREAD

**Issue by kingeasternsun** [nats-io/nats-site#403]
https://nats.io/documentation/writing_applications/concepts/ says:
```
NATS supports two flavors of request reply messaging: point-to-point or one-to-many. Point-to-point involves the fastest or first to respond. In a one-to-many exchange, you set a limit on the number of responses the requestor may receive.
```

But I can not found any doc or example related to "one to many ", can u provide this?

**Comment by gcolliso** [comment]
Documentation has been updated and now located at https://nats-io.github.io/docs.

Check out the new [concepts doc ](https://nats-io.github.io/docs/developer/concepts/intro.html) and the [Publish Subscribe](https://nats-io.github.io/docs/developer/concepts/pubsub.html) documentation and tutorial for one to many.
