### ISSUE TITLE
Is NATS a company or open source project?

### ISSUE THREAD

**Issue by JensRantil** [nats-io/nats-site#448]
I just read

> Our team has decades of experience in distributed systems messaging, and are here to help you implement and maximize the benefits of a lightweight messaging system in any environment. Support is available for the NATS Server, and the Synadia supported clients listed here.
>
> Contact us today to learn more about how we can help you get the most out of NATS in your environment.

on https://nats.io/support/. Given that NATS is an CNCF project, I think this text likely should be something like

> Contact [Synadia](https://synadia.com/) for professional support on NATS.

, right?

**Comment by gcolliso** [comment]
Updated the support page on your suggestion. Thank you!
