### ISSUE TITLE
NATS doesn't offer TCP Reliability as stated in FAQ

### ISSUE THREAD

**Issue by meiswjn** [nats-io/nats-site#488]
> 
> FAQ Question 
> "Does NATS gurantee message delivery?"
> Reply:
> NATS implements what is commonly referred to as **"at-most-once**" delivery. This means that messages are guaranteed to arrive intact, in order from a given publisher, but not across different publishers. NATS does everything required to remain on and provide a dial-tone. However, if a subscriber is problematic or goes offline it will not receive messages, as the basic NATS platform is a simple pub-sub transport system that offers only **TCP reliability**.

I'm really no expert at this topic but doesn't basic NATS not send any acknowledgments at all -> fire and forget?
TCP uses acknowledgements and tries to redeliver messages. (https://en.wikipedia.org/wiki/Transmission_Control_Protocol)

I think basic NATS is closer to UDP's reliability and NATS Streaming can be compared to TCP.

**Comment by meiswjn** [comment]
Actually, can you even say basic NATS provides at-most-once delivery? If there are multiple subscribers, it will be sent to all of them unless a queue is used... or is the at-most-once related to the delivery attempts?

**Comment by ColinSullivan1** [comment]
Thanks for using NATS!  You are correct in the context of what happens in a TCP connection that remains established with acks/resends for error checking and to maintain ordering.  However, In TCP, if a connection is broken, packets in flight may not be redelivered when the application re-establishes a connection to its server, giving it at most once delivery semantics from the context of the application.  In NATS, at-most-once is in the context of delivery to any particular subscriber who is supposed to receive the message.

NATS streaming goes further, where a connection can be completely severed, and upon restoring or recreating the connection, all missed messages will be redelivered.  There's a small window where a message can be redelivered, so it has at least once delivery semantics.

I agree that the publish/subscribe fanout is like UDP (except in NATS you can cross a subnet easily).

**Comment by meiswjn** [comment]
Cheers, that explains it pretty well :)
