### ISSUE TITLE
Consolidate nats-site, nats-docs and nats-theme into one repo.

### ISSUE THREAD

**Issue by mcqueary** [nats-io/nats-site#59]
/cc @bjflanne @lparis

From personal experience and talking to @chriscasper, keeping the site, docs and theme in 3 separate repos is unnecessarily cumbersome for contributors/collaborators and also in terms of publishing the site. Is there any reason we can't combine all this back into a single repo: nats-site? I don't see any down-side.

**Comment by ColinSullivan1** [comment]
+1

**Comment by chriscasper** [comment]
This is now completed.
