### ISSUE TITLE
Add NATS and STAN Ballerina lang clients 

### ISSUE THREAD

**Issue by aashikam** [nats-io/nats-site#613]
## Description

[Ballerina](https://ballerina.io/) lang provides support for NATS and NATS streaming. It would be great if you could mention the Ballerina clients for NATS and NATS streaming in nats.io.  

## References

**Ballerina:**
Site: https://ballerina.io/
Central: https://swanlake.central.ballerina.io/ 

**NATS client:** 
Package: **ballerinax/nats**
Latest: https://swanlake.central.ballerina.io/ballerinax/stan/1.1.0-alpha5 
Source: https://github.com/ballerina-platform/module-ballerinax-nats 

**NATS streaming client:** 
Package: **ballerinax/stan**
Latest: https://swanlake.central.ballerina.io/ballerinax/nats/1.1.0-alpha5
Source: https://github.com/ballerina-platform/module-ballerinax-stan

**Comment by gcolliso** [comment]
Thank you @aashikam - Ballerina for NATS & STAN have been added to our Connectors & Utilities https://nats.io/download/#connectors-and-utilities

**Comment by aashikam** [comment]
@gcolliso Nice! 
Another small suggestion: https://github.com/nats-io/nats-site/issues/615
