### ISSUE TITLE
Ballerina clients named as servers

### ISSUE THREAD

**Issue by aashikam** [nats-io/nats-site#615]
Ballerina NATS client and Ballerina Streaming client are mentioned as Ballerina NATS server and Ballerina NATS Streaming server in https://nats.io/download/#connectors-and-utilities. These two packages are community clients for connecting to NATS and NATS streaming servers. It would be even better they could be mentioned under community clients :)

**Comment by gcolliso** [comment]
@aashikam I've moved the Ballerina clients to the Community Client lists per your request

**Comment by aashikam** [comment]
Great!

**Comment by aashikam** [comment]
Hey, I see these were removed? Any reason?

**Comment by gcolliso** [comment]
@aashikam the Ballerina clients were not removed purposefully. This may have occurred with the migrating of the nats-site to a new UI. I will be sure to get them added back to the client lists asap.

**Comment by gcolliso** [comment]
added back in #680
