### ISSUE TITLE
Homepage isn't mobile friendly: excessive horizontal scrolling is possible

### ISSUE THREAD

**Issue by chalin** [nats-io/nats-site#632]
For example, I can get a view like this:

> <img src="https://user-images.githubusercontent.com/4140793/116096654-76d63180-a677-11eb-87fb-78bc7ba90f92.png" width=400>

**Comment by chalin** [comment]
Btw, we can get the same issue to appear on desktop when the view is narrow enough.

**Comment by gcolliso** [comment]
Is there a way to get the end user logos on the home page to be more consistent in sizing in mobile or narrow screen viewing?

**Comment by chalin** [comment]
Closed by  #633. Let's track other homepage and/or mobile-design issues via separate issues.
