### ISSUE TITLE
Trying to download the latest nats server gives a 404

### ISSUE THREAD

**Issue by aashikam** [nats-io/nats-site#645]
URL: https://github.com/nats-io/nats-io/nats-server/releases/latest
<img width="1404" alt="Screenshot 2021-05-02 at 10 55 28" src="https://user-images.githubusercontent.com/39673615/116803421-20646980-ab35-11eb-87c5-3709482ff579.png">

**Comment by matthiashanel** [comment]
you have nats-io/nats-io instead of nats-io
Try this url instead: https://github.com/nats-io/nats-server/releases/latest
