### ISSUE TITLE
Review and correct the NATS Client Development Guide

### ISSUE THREAD

**Issue by mcqueary** [nats-io/nats-site#66]
There are a number of inaccuracies and grammar errors in the document that need to be cleaned up. 
- Need to remove second-person narrative ("you [...]") in multiple places.
- Link to the Protocol Guide as the authoritative source for specific syntax and meaning, vs. re-defining it, possibly in a conflicting or confusing way, here.
- Re-focus the document on the 5,000 foot view of client structure and conventions, possibly including some FAQs that are client-dev specific, e.g.: Why do you send a `PING`-`PONG` during the `CONNECT` sequence?

**Comment by gcolliso** [comment]
closing this issue as is irrelevant at this time - docs have been revamped June 2019
