### ISSUE TITLE
No blog this year?

### ISSUE THREAD

**Issue by dimaqq** [nats-io/nats-site#772]
I took a peek at the blog and the latest article is from Oct 2021.
Now it will be notably harder for me to convince other devs to try NATS.

**Comment by wallyqs** [comment]
a great resource to keep up to date with NATS right now is @bruth's newsletter => https://www.byronruth.com/nats-weekly-43/

**Comment by bruth** [comment]
Hi @dimaqq, totally acknowledged! I recently joined Synadia and the NATS team to focus on producing more content. So more will definitely be coming.

As @wallyqs pointed out there is a weekly newsletter I have maintained and other blog posts on my site (all prior to me joining).  There is also https://natsbyexample.com which has a lot of in-depth examples.

If you have specific topics in mind, please let me know!

**Comment by bruth** [comment]
@dimaqq Purely coincidence, but the 2.9 server release was just [announced on the blog](https://nats.io/blog/nats-server-29-release/) :wink:
