### ISSUE TITLE
Google Analytics completely gone?

### ISSUE THREAD

**Issue by chalin** [nats-io/nats-site#787]
Hi, I'm working on [migrating CNCF projects from UA to GA4](https://github.com/cncf/techdocs/issues/108). It seems that GA was replaced in favor of FA via:

- #784

But the GA ID still appears in the `config.toml` file https://github.com/nats-io/nats-site/blob/a3766d53eb132b4616e46def0e16ee7585525d49/config.toml#L18

Which I figured could have been an omission, but the GA ID also still appears in nats.io page HTML. Is this because FA uses the same site ID, or is the ID used for another purpose?

If GA is completely gone, can you grant the CNCF access to your FA account?

/cc @nate-double-u @caniszczyk

**Comment by gcolliso** [comment]
@chalin I can give you access to the shared link but would rather not publish here. Could you email me? Ginger at nats.io

**Comment by chalin** [comment]
Thanks, an email is on its way.

Shall I leave this open as a reminder to clean out the `config.toml` file?

**Comment by gcolliso** [comment]
Sure, thanks!

**Comment by chalin** [comment]
FYI, if you look at the HTML of any site page you'll see

```html
<script>
function getGAKey(){return "UA-111730698-1";}
function getGAKeyDisableKey(){return "ga-disable-"+getGAKey();}
function getCookie(){var cookies=document.cookie;var a=cookies.split(";");return a.find(function(e){e=e.trim();return e.startsWith("ga-disable=");});}
function updateCheckbox(tc){var checked=false;if(tc){checked=tc.trim().split('=')[1]=="true";}
$('#disable_analytics').prop('checked',checked);return checked;}
function addGA(){if(!$('#gascript').length){var s=document.createElement('script',{async:'',id:'gascript'});s.type='text/javascript';s.src='https://www.google-analytics.com/analytics.js';$('body').append(s);}}
function checkTrack(){var tc=getCookie();var disable=updateCheckbox(tc);window[getGAKeyDisableKey()]=disable;if(!tc){openPrivacy(tc);}else{addGA();}}
function openPrivacy(tc){var gdprSel=$('#gdpr');gdprSel.removeClass('hide');return handleSizes();}
var paddingTop=0;function handleSizes(){var gdprSel=$('#gdpr');if(!gdprSel.hasClass('hide')){var h=gdprSel.innerHeight();var body=$('body');var pt=parseInt(body.css('padding-top'),10);if(paddingTop===0){paddingTop=pt;}
body.css("padding-top",(paddingTop+h)+"px");$('#nav').css({top:h+"px"});gdprSel.css({top:0,position:"fixed",zIndex:2000,width:"100%"});}}
$(window).resize(handleSizes);$(window).load(function(){var sel=$('#disable_analytics');if(sel.length){sel.change(function(){deleteCookie("ga-disable");if($(this).is(':checked')){disableAnalytics();}else{enableAnalytics();}
return false;});};});function disableAnalytics(){window[getGAKeyDisableKey()]=true;closeRibbon();var d=new Date();d.setFullYear(d.getFullYear()+1);document.cookie="ga-disable=true; expires="+oneYearFromNow().toUTCString()+"; path=/";addGA();}
function enableAnalytics(){window[getGAKeyDisableKey()]=false;closeRibbon();var d=new Date();d.setFullYear(d.getFullYear()+1);document.cookie="ga-disable=false; expires="+oneYearFromNow().toUTCString()+"; path=/";addGA();}
function oneYearFromNow(){var d=new Date();d.setFullYear(d.getFullYear()+1);return d;}
function closeRibbon(){var gdprSel=$('#gdpr');if(!gdprSel.hasClass('hide')){$('#nav').css({top:"0px"});gdprSel.addClass('hide');if(paddingTop){$('body').css("padding-top",paddingTop+"px");}
if(getCookie()===undefined){enableAnalytics();}}}
function deleteCookie(name){document.cookie=name+'=; expires=Thu, 01 Jan 1970 00:00:01 GMT;';}</script><script>window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;ga('create',getGAKey(),{cookieExpires:0});ga('set','anonymizeIp',true);ga('send','pageview');
</script>
```

So it seems that GA code is still being generated.

**Comment by gcolliso** [comment]
@chalin I think we may be going back to GA at the end of this month for the nats.io site. Do you know if there is still a requirement to have a cookies/GDPR/Privacy banner for the new GA4? We appreciate Fathom for that reason.

**Comment by chalin** [comment]
Hi @gcolliso. At the moment, the banner/popup guidance I've been given (and will [hopefully be working on soon](https://github.com/open-telemetry/opentelemetry.io/issues/1636)) is along the lines of the popup shown on the cncf.io site, which reads like:

> This website stores data such as cookies to enable essential site functionality, as well as marketing, personalization, and analytics. By remaining on this website you indicate your consent. [Cookie Policy](https://www.linuxfoundation.org/privacy-policy/)

I hope that this helps.
