### ISSUE TITLE
Document various server binary distribution channels

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats-site#89]
Document installing the NATS server from other channels.

homebrew (http://brewformulas.org/Gnatsd):
`brew install gnatsd`

Chocolately (https://chocolatey.org/packages/gnatsd):
`choco install gnatsd`

**Comment by mcqueary** [comment]
This also goes for nats-streaming-server:

homebrew (http://brewformulas.org/Gnatsd):
brew install nats-streaming-server

Chocolately (https://chocolatey.org/packages/nats-streaming-server):
choco install nats-streaming-server
