### ISSUE TITLE
Synadia Platform link 404 from Support Page

### ISSUE THREAD

**Issue by rtmorgan** [nats-io/nats-site#917]
The current Synadia Platform link (https://www.synadia.com/control-plane) under Commercial Support and Services on the Support page (https://nats.io/support/) results in a 404 page.

https://github.com/nats-io/nats-site/blob/4e0fbdc227f5dbeec76393ead65a0646bc66c492/content/support.md?plain=1#L17

**Comment by gcolliso** [comment]
Thanks @rtmorgan for the notification. The link has been updated.
