### ISSUE TITLE
Section for subjects and wildcards

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats-site#96]
We should have a section in the documentation focusing on subject usage and wildcards.

A good place in the documentation could be a new list item under concepts, near publish/subscribe.

Content can be garnered from:
https://github.com/nats-io/nats#wildcard-subscriptions
https://github.com/nats-io/csnats#wildcard-subscriptions
https://groups.google.com/forum/#!topic/natsio/zeQKbVNi0rc
https://groups.google.com/forum/#!topic/natsio/z12Afncvslc
https://groups.google.com/forum/#!topic/natsio/4hIGmO48ERQ

@lparis, if you can get to this, that'd be great, otherwise I will when I get a chance.

**Comment by gcolliso** [comment]
Closing issue as documentation has been moved to nats-io/docs. Subject/wildard documentation added here:
developer/concepts/subjects.html
developer/sending/replyto.html
developer/receiving/wildcards.html
