### ISSUE TITLE
Seems that documentation lacks section on TLS

### ISSUE THREAD

**Issue by kozlovic** [nats-io/nats-site#97]
Did not find a section on TLS. Precisely, several users already had issues due to the lack of understanding that even when servers and clients are configured to use TLS, the beginning of the protocol is done in plain text.

Some info sent to an user on slack:

```
The beginning of the protocol exchange between server and client is done in plain text.
When the client creates the TCP connection, the server will, in response, send in plain text its “INFO” protocol message.
From this protocol, the client knows if the server requires or not TLS. If the client is not configured for TLS and server asks, the connect will fail before even attempting to send anything to the server.
And vice-versa.
If server and client are configured for TLS, the client, after receiving the INFO protocol, will switch the connection to TLS and then send its CONNECT protocol.
```

**Comment by mcqueary** [comment]
Should be noted in both the TLS section as well as in the (to-be-rewritten) client development guide.

**Comment by gcolliso** [comment]
Closing issue - documentation moved to nats-io/docs. TLS documentation here:
nats_server/tls.md
nats_server/cluster_tls.md
developer/security/tls.md
